class CreateMunicipios < ActiveRecord::Migration[5.2]
  def change
    create_table :municipios do |t|
      t.string :nome
      t.references :provincia, foreign_key: true

      t.timestamps
    end

    Municipio.all.each(&:destroy)
    Provincia.all.each(&:destroy)
    Pais.all.each(&:destroy)

    pais           = Pais.create(nome: "Angola")
    
    bie            = Provincia.create(nome: "Bié", pais_id: pais.id)
    bengo          = Provincia.create(nome: "Bengo", pais_id: pais.id)
    benguela       = Provincia.create(nome: "Benguela", pais_id: pais.id)
    cabinda        = Provincia.create(nome: "Cabinda", pais_id: pais.id)
    cunene         = Provincia.create(nome: "Cunene", pais_id: pais.id)
    huila          = Provincia.create(nome: "Huila", pais_id: pais.id)
    huambo         = Provincia.create(nome: "Huambo", pais_id: pais.id)
    kwanza_sul     = Provincia.create(nome: "Kwanza Sul", pais_id: pais.id)
    kwanza_norte   = Provincia.create(nome: "Kwanza Norte", pais_id: pais.id)
    kuando_kubango = Provincia.create(nome: "Kuando Kubango", pais_id: pais.id)
    luanda         = Provincia.create(nome: "Luanda", pais_id: pais.id)
    lunda_norte    = Provincia.create(nome: "Lunda Norte", pais_id: pais.id)
    lunda_sul      = Provincia.create(nome: "Lunda sul", pais_id: pais.id)
    malanje        = Provincia.create(nome: "Malanje", pais_id: pais.id)
    moxico         = Provincia.create(nome: "Moxico", pais_id: pais.id)
    namibe         = Provincia.create(nome: "Namibe", pais_id: pais.id)
    uige           = Provincia.create(nome: "Uíge", pais_id: pais.id)
    zaire          = Provincia.create(nome: "Zaire", pais_id: pais.id)

    Municipio.create(nome: "Ambriz", provincia_id: 	bengo.id)
    Municipio.create(nome: "Bula Atumba", provincia_id: 	bengo.id)
    Municipio.create(nome: "Dande", provincia_id: 	bengo.id)
    Municipio.create(nome: "Dembos", provincia_id: 	bengo.id)
    Municipio.create(nome: "Nambuangongo", provincia_id: 	bengo.id)
    Municipio.create(nome: "Pango Aluquém", provincia_id: 	bengo.id)
    Municipio.create(nome: "Balombo", provincia_id: 	benguela.id)
    Municipio.create(nome: "Baía Farta", provincia_id: 	benguela.id)
    Municipio.create(nome: "Benguela", provincia_id: 	benguela.id)
    Municipio.create(nome: "Bocoio", provincia_id: 	benguela.id)
    Municipio.create(nome: "Caimbambo", provincia_id: 	benguela.id)
    Municipio.create(nome: "Chongorói", provincia_id: 	benguela.id)
    Municipio.create(nome: "Cubal", provincia_id: 	benguela.id)
    Municipio.create(nome: "Ganda", provincia_id: 	benguela.id)
    Municipio.create(nome: "Lobito", provincia_id: 	benguela.id)
    Municipio.create(nome: "Andulo", provincia_id: 	bie.id)
    Municipio.create(nome: "Camacupa", provincia_id: 	bie.id)
    Municipio.create(nome: "Catabola", provincia_id: 	bie.id)
    Municipio.create(nome: "Chinguar", provincia_id: 	bie.id)
    Municipio.create(nome: "Chitembo", provincia_id: 	bie.id)
    Municipio.create(nome: "Cuemba", provincia_id: 	bie.id)
    Municipio.create(nome: "Cunhinga", provincia_id: 	bie.id)
    Municipio.create(nome: "Kuito", provincia_id: 	bie.id)
    Municipio.create(nome: "Nharea", provincia_id: 	bie.id)
    Municipio.create(nome: "Belize", provincia_id: 	cabinda.id)
    Municipio.create(nome: "Buco-Zau", provincia_id: 	cabinda.id)
    Municipio.create(nome: "Cabinda", provincia_id: 	cabinda.id)
    Municipio.create(nome: "Cacongo", provincia_id: 	cabinda.id)
    Municipio.create(nome: "Calai", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Cuangar", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Cuchi", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Cuito Cuanavale", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Dirico", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Longa", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Mavinga", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Menongue", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Rivungo", provincia_id: 	kuando_kubango.id)
    Municipio.create(nome: "Ambaca", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Banga", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Bolongongo", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Cambambe", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Cazengo", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Golungo Alto", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Gonguembo", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Lucala", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Quiculungo", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Samba Caju", provincia_id: 	kwanza_norte.id)
    Municipio.create(nome: "Amboim", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Cassongue", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Cela", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Conda", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Ebo", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Libolo", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Mussende", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Quibala", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Quilenda", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Seles", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Sumbe", provincia_id: 	kwanza_sul.id)
    Municipio.create(nome: "Cahama", provincia_id: 	cunene.id)
    Municipio.create(nome: "Cuanhama", provincia_id: 	cunene.id)
    Municipio.create(nome: "Curoca", provincia_id: 	cunene.id)
    Municipio.create(nome: "Cuvelai", provincia_id: 	cunene.id)
    Municipio.create(nome: "Namacunde", provincia_id: 	cunene.id)
    Municipio.create(nome: "Ombadja", provincia_id: 	cunene.id)
    Municipio.create(nome: "Bailundo", provincia_id: 	huambo.id)
    Municipio.create(nome: "Catchiungo", provincia_id: 	huambo.id)
    Municipio.create(nome: "Caála", provincia_id: 	huambo.id)
    Municipio.create(nome: "Ekunha", provincia_id: 	huambo.id)
    Municipio.create(nome: "Huambo", provincia_id: 	huambo.id)
    Municipio.create(nome: "Londuimbale", provincia_id: 	huambo.id)
    Municipio.create(nome: "Longonjo", provincia_id: 	huambo.id)
    Municipio.create(nome: "Mungo", provincia_id: 	huambo.id)
    Municipio.create(nome: "Tchicala-Tcholoanga", provincia_id: 	huambo.id)
    Municipio.create(nome: "Tchindjenje", provincia_id: 	huambo.id)
    Municipio.create(nome: "Ucuma", provincia_id: 	huambo.id)
    Municipio.create(nome: "Caconda", provincia_id: 	huila.id)
    Municipio.create(nome: "Caluquembe", provincia_id: 	huila.id)
    Municipio.create(nome: "Chiange", provincia_id: 	huila.id)
    Municipio.create(nome: "Chibia", provincia_id: 	huila.id)
    Municipio.create(nome: "Chicomba", provincia_id: 	huila.id)
    Municipio.create(nome: "Chipindo", provincia_id: 	huila.id)
    Municipio.create(nome: "Cuvango", provincia_id: 	huila.id)
    Municipio.create(nome: "Humpata", provincia_id: 	huila.id)
    Municipio.create(nome: "Jamba", provincia_id: 	huila.id)
    Municipio.create(nome: "Lubango", provincia_id: 	huila.id)
    Municipio.create(nome: "Matala", provincia_id: 	huila.id)
    Municipio.create(nome: "Quilengues", provincia_id: 	huila.id)
    Municipio.create(nome: "Quipungo", provincia_id: 	huila.id)
    Municipio.create(nome: "Belas", provincia_id: 	luanda.id)
    Municipio.create(nome: "Talatona", provincia_id: 	luanda.id)
    Municipio.create(nome: "Cacuaco", provincia_id: 	luanda.id)
    Municipio.create(nome: "Cazenga", provincia_id: 	luanda.id)
    Municipio.create(nome: "Ícolo e Bengo", provincia_id: 	luanda.id)
    Municipio.create(nome: "Luanda", provincia_id: 	luanda.id)
    Municipio.create(nome: "Quissama", provincia_id: 	luanda.id)
    Municipio.create(nome: "Viana", provincia_id: 	luanda.id)
    Municipio.create(nome: "Capenda-Camulemba", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Caungula", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Chitato", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Cuango", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Cuílo", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Lubalo", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Xá-Muteba", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Cambulo", provincia_id: 	lunda_norte.id)
    Municipio.create(nome: "Cacolo", provincia_id: 	lunda_sul.id)
    Municipio.create(nome: "Dala", provincia_id: 	lunda_sul.id)
    Municipio.create(nome: "Muconda", provincia_id: 	lunda_sul.id)
    Municipio.create(nome: "Saurimo", provincia_id: 	lunda_sul.id)
    Municipio.create(nome: "Cacuso", provincia_id: 	malanje.id)
    Municipio.create(nome: "Calandula", provincia_id: 	malanje.id)
    Municipio.create(nome: "Cambundi-Catembo", provincia_id: 	malanje.id)
    Municipio.create(nome: "Cangandala", provincia_id: 	malanje.id)
    Municipio.create(nome: "Caombo", provincia_id: 	malanje.id)
    Municipio.create(nome: "Cuaba Nzogo", provincia_id: 	malanje.id)
    Municipio.create(nome: "Cunda-Dia-Baze", provincia_id: 	malanje.id)
    Municipio.create(nome: "Luquembo", provincia_id: 	malanje.id)
    Municipio.create(nome: "Malanje", provincia_id: 	malanje.id)
    Municipio.create(nome: "Marimba", provincia_id: 	malanje.id)
    Municipio.create(nome: "Massango", provincia_id: 	malanje.id)
    Municipio.create(nome: "Mucari", provincia_id: 	malanje.id)
    Municipio.create(nome: "Quela", provincia_id: 	malanje.id)
    Municipio.create(nome: "Quirima", provincia_id: 	malanje.id)
    Municipio.create(nome: "Alto Zambeze", provincia_id: 	moxico.id)
    Municipio.create(nome: "Bundas", provincia_id: 	moxico.id)
    Municipio.create(nome: "Camanongue", provincia_id: 	moxico.id)
    Municipio.create(nome: "Luacano", provincia_id: 	moxico.id)
    Municipio.create(nome: "Luau", provincia_id: 	moxico.id)
    Municipio.create(nome: "Luchazes", provincia_id: 	moxico.id)
    Municipio.create(nome: "Léua", provincia_id: 	moxico.id)
    Municipio.create(nome: "Moxico", provincia_id: 	moxico.id)
    Municipio.create(nome: "Bibala", provincia_id: 	namibe.id)
    Municipio.create(nome: "Camucuio", provincia_id: 	namibe.id)
    Municipio.create(nome: "Moçâmedes", provincia_id: 	namibe.id)
    Municipio.create(nome: "Tômbua", provincia_id: 	namibe.id)
    Municipio.create(nome: "Virei", provincia_id: 	namibe.id)
    Municipio.create(nome: "Alto Cauale", provincia_id: 	uige.id)
    Municipio.create(nome: "Ambuíla", provincia_id: 	uige.id)
    Municipio.create(nome: "Bembe", provincia_id: 	uige.id)
    Municipio.create(nome: "Buengas", provincia_id: 	uige.id)
    Municipio.create(nome: "Damba", provincia_id: 	uige.id)
    Municipio.create(nome: "Macocola", provincia_id: 	uige.id)
    Municipio.create(nome: "Mucaba", provincia_id: 	uige.id)
    Municipio.create(nome: "Negage", provincia_id: 	uige.id)
    Municipio.create(nome: "Puri", provincia_id: 	uige.id)
    Municipio.create(nome: "Quimbele", provincia_id: 	uige.id)
    Municipio.create(nome: "Quitexe", provincia_id: 	uige.id)
    Municipio.create(nome: "Sanza Pombo", provincia_id: 	uige.id)
    Municipio.create(nome: "Songo", provincia_id: 	uige.id)
    Municipio.create(nome: "Uíge", provincia_id: 	uige.id)
    Municipio.create(nome: "Zombo", provincia_id: 	uige.id)
    Municipio.create(nome: "Cuimba", provincia_id: 	zaire.id)
    Municipio.create(nome: "M'Banza Kongo", provincia_id: 	zaire.id)
    Municipio.create(nome: "Noqui", provincia_id: 	zaire.id)
    Municipio.create(nome: "N'Zeto", provincia_id: 	zaire.id)
    Municipio.create(nome: "Soyo", provincia_id: 	zaire.id)
  end
end
